proveedores/app/urls.py
from django.urls import path
from .import views

app_name = "app"

urlpatterns = [
    path("",views.index,name="index"),
    path("createprov/", views.new_prov, name="newprov"),
    path("viewprov/", views.view_prov, name="viewprov"), 
    path("deleteprov/<id>", views.delete_prov, name="deleteprov"),
    
    ]

proveedores/proveedores/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("app.urls")),
]

proveedores/app/models.py
from django.db import models

class TypeProveedor(models.TextChoices):
    Hotel       = "Hotel"
    Pista       = "Pista"
    Complemento = "Complemento"


class Proveedor(models.Model):
    name           = models.CharField(max_length = 128)
    email          = models.EmailField()
    phone          = models.CharField(max_length = 128)
    type_proveedor = models.TextField(choices=TypeProveedor.choices)
    active         = models.BooleanField()
    created_at     = models.DateTimeField(auto_now = True)
    update_at      = models.DateTimeField(auto_now_add = True)

    

proveedores/app/forms.py
from django import forms
from app.models import Proveedor

class FormularioProveedor(forms.ModelForm):
    class Meta: 
        model = Proveedor
        fields = "__all__"
        

proveedores/app/views.py
from django.shortcuts import render, redirect
from . import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Proveedor



def index(request):
    return render (request,"index.html")

def new_prov(request):
    if request.method == "POST":
        form = forms.FormularioProveedor(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("app:newprov"))
    else:
        form = forms.FormularioProveedor
    ctx = {"form":form}
    return render (request,"createprov.html",ctx)

def view_prov(request):
    prov = Proveedor.objects.all()
    ctx = {"prov":prov}
    return render (request,"viewprov.html",ctx)

def delete_prov(request, id):
    prov = Proveedor.objects.get(id=id)
    prov.delete()
    return HttpResponseRedirect(reverse("viewprov"))

proveedores/app/templates/createprov.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo proveedor</title>
</head>
<body>
    <h1>Nuevo proveedor</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value ="Añadir proveedor" >
    </form>
</body>
</html>

proveedores/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a class="nav-link" href="{% url "app:newprov" %}">Agregar proveedor</a><br>
    <a class="nav-link" href="{% url "app:viewprov" %}">Ver proveedores</a>
    

</body>
</html>

proveedores/app/templates/viewprov.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2 style="text-align: center">Proveedores</h2>
    <table>
        <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Email</th>
              <th>Telefono</th>
              <th>Tipo proveedor</th>
              <th>Activo</th>
              <th>Creado</th>
              <th>Actualizado</th>
            </tr>
        </thead>
          <tbody>
            {% for prov in prov %}
            <tr>
                <td>{{prov.id}}</td>
                <td>{{prov.name}}</td>
                <td>{{prov.email}}</td>
                <td>{{prov.phone}}</td>
                <td>{{prov.type_proveedor}}</td>
                <td>{{prov.active}}</td>
                <td>{{prov.created_at}}</td>
                <td>{{prov.update_at}}</td>
            </tr>
            {%endfor%}
            
          </tbody>
    </table>
      
</body>
</html>